on:
  push:
    branches:
     - meu-chatbot
     - main


jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build And Deploy
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                   ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"          # pasta do front-end
          api_location: "api"          # pasta das Azure Functions
          output_location: "dist"     # pasta gerada pelo build (React → build; Vue → dist)
