name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - meu-chatbot

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build And Deploy
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                   ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"       # ou "api" se você tiver Azure Functions
          output_location: "src"
