# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - udoni-chatbot-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://udonacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_20c2b6477ee744a7aff976083d6237c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9b392720affb4918ac8d2371d1398358 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: udonacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_20c2b6477ee744a7aff976083d6237c8 }}/udon-chatbot-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'udoni-chatbot-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c4b72076370c4e54a1b27ea16fd4b56b }}
        images: 'udonacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_20c2b6477ee744a7aff976083d6237c8 }}/udon-chatbot-image:${{ github.sha }}'